///|/ Copyright (c) Prusa Research 2020 - 2023 Tomáš Mészáros @tamasmeszaros, Lukáš Matěna @lukasmatena
///|/
///|/ PrusaSlicer is released under the terms of the AGPLv3 or higher
///|/
#ifndef SLA_SUPPORTPOINT_HPP
#define SLA_SUPPORTPOINT_HPP

#include <libslic3r/Point.hpp>

namespace Slic3r::sla {

// An enum to keep track of where the current points on the ModelObject came from.
enum class PointsStatus {
    NoPoints,           // No points were generated so far.
    Generating,     // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated,  // Points were autogenerated (i.e. copied from the backend).
    UserModified    // User has done some edits.
};

// Reason of automatic support placement usage
enum class SupportPointType {
    manual_add,
    island, // no move, island should be grouped
    slope,
    //thin,
    //stability,
    //edge
};

/// <summary>
/// Stereolithography(SLA) support point
/// </summary>
struct SupportPoint
{
    // Position on model surface
    Vec3f pos = Vec3f::Zero(); // [in mm]

    // radius of the touching interface
    // Also define force it must keep
    float head_front_radius = 0.f; // [in mm]

    // type
    SupportPointType type{SupportPointType::manual_add};

    // Compatibility with Orca's existing 3MF/AMF format and SLA editor.
    // The latest generator represents this information with `type == island`.
    bool is_new_island = false;

    SupportPoint() = default;

    SupportPoint(float pos_x, float pos_y, float pos_z, float head_radius,
                 bool new_island = false)
        : pos(pos_x, pos_y, pos_z)
        , head_front_radius(head_radius)
        , type(new_island ? SupportPointType::island : SupportPointType::manual_add)
        , is_new_island(new_island)
    {}

    SupportPoint(Vec3f position, float head_radius, bool new_island = false)
        : pos(std::move(position))
        , head_front_radius(head_radius)
        , type(new_island ? SupportPointType::island : SupportPointType::manual_add)
        , is_new_island(new_island)
    {}

    SupportPoint(Vec3f position, float head_radius, SupportPointType point_type)
        : pos(std::move(position))
        , head_front_radius(head_radius)
        , type(point_type)
        , is_new_island(point_type == SupportPointType::island)
    {}

    explicit SupportPoint(Eigen::Matrix<float, 5, 1, Eigen::DontAlign> data)
        : SupportPoint(data(0), data(1), data(2), data(3), data(4) != 0.f)
    {}
    
    bool is_island() const { return type == SupportPointType::island || is_new_island; }
    template<class Archive> void serialize(Archive &ar){
        // Keep the existing Orca cache/archive layout.
        ar(pos, head_front_radius, is_new_island);
    }

    // unsaved changes + cache invalidation
    bool operator==(const SupportPoint &sp) const {
        float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        return (pos == sp.pos) && rdiff < float(EPSILON) &&
               type == sp.type && is_new_island == sp.is_new_island;
    }

    bool operator!=(const SupportPoint &sp) const { return !(sp == (*this)); }

};
using SupportPoints = std::vector<SupportPoint>;

} // namespace Slic3r::sla

#endif // SUPPORTPOINT_HPP
