param(
    [string] $RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [string] $SlicerPath = "",
    [string] $OutputRoot = "",
    [ValidateRange(1, 5000)]
    [int] $CaseCount = 320,
    [int] $Seed = 250802,
    [ValidateRange(10, 600)]
    [int] $SliceTimeoutSeconds = 180,
    [switch] $PerCaseVulkanDiagnostics,
    [switch] $PlanOnly
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$Invariant = [Globalization.CultureInfo]::InvariantCulture
$RepoRoot = [IO.Path]::GetFullPath($RepoRoot)
if ([string]::IsNullOrWhiteSpace($SlicerPath)) {
    $SlicerPath = Join-Path $RepoRoot 'build\src\Release\magpie-slicer.exe'
}
if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    $OutputRoot = Join-Path $RepoRoot 'build\verification\vulkan-cpu-matrix'
}
$SlicerPath = [IO.Path]::GetFullPath($SlicerPath)
$runRoot = Join-Path ([IO.Path]::GetFullPath($OutputRoot)) (Get-Date -Format 'yyyyMMdd-HHmmss')
New-Item -ItemType Directory -Force -Path $runRoot | Out-Null

function Set-JsonProperty($Object, [string] $Name, $Value) {
    if ($null -eq $Object.PSObject.Properties[$Name]) {
        $Object | Add-Member -NotePropertyName $Name -NotePropertyValue $Value
    } else {
        $Object.$Name = $Value
    }
}

function Select-RandomValue([Random] $Random, [object[]] $Values) {
    return $Values[$Random.Next(0, $Values.Count)]
}

function Find-FilamentProfile([string] $Name) {
    foreach ($root in @(
        (Join-Path $RepoRoot 'resources\profiles'),
        (Join-Path $RepoRoot 'build\src\Release\resources\profiles')
    )) {
        if (-not (Test-Path -LiteralPath $root -PathType Container)) { continue }
        $match = Get-ChildItem -LiteralPath $root -Recurse -File -Filter ($Name + '.json') |
            Select-Object -First 1
        if ($null -ne $match) { return $match.FullName }
    }
    throw "Filament profile not found: $Name"
}

function Get-TextSha256([string] $Text) {
    $bytes = [Text.Encoding]::UTF8.GetBytes($Text)
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        return ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-', '').ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

function Analyze-Gcode([string] $Path) {
    $canonical = [Text.StringBuilder]::new()
    $motion = [Text.StringBuilder]::new()
    $lineCount = 0
    $motionCount = 0
    $extrusionCount = 0
    $toolChanges = 0
    $nonFinite = 0
    foreach ($raw in [IO.File]::ReadLines($Path)) {
        $line = $raw.TrimEnd()
        ++$lineCount
        if ($line -match '(?i)(^; generated by .+ on \d{4}-\d{2}-\d{2}|generated at|generation time|timestamp|creation date|slicing time|processing time)') {
            continue
        }
        [void]$canonical.Append($line).Append("`n")
        $command = ($line -split ';', 2)[0].Trim()
        if ($command -match '^(?:G0|G1|G2|G3|G5|T\d+|M10[4679]|M106|M107)(?:\s|$)') {
            [void]$motion.Append($command).Append("`n")
            ++$motionCount
        }
        if ($command -match '^G[0123]\s' -and $command -match '(?:^|\s)E-?(?:\d|\.)') { ++$extrusionCount }
        if ($command -match '^T\d+(?:\s|$)') { ++$toolChanges }
        if ($command -match '(?i)(?:^|[\s=,])(?:nan|[+-]?inf(?:inity)?)(?=$|[\s,])') { ++$nonFinite }
    }
    [pscustomobject]@{
        canonical_sha256 = Get-TextSha256 $canonical.ToString()
        motion_sha256 = Get-TextSha256 $motion.ToString()
        bytes = (Get-Item -LiteralPath $Path).Length
        lines = $lineCount
        motion_commands = $motionCount
        extrusion_commands = $extrusionCount
        tool_changes = $toolChanges
        non_finite = $nonFinite
    }
}

function Set-NozzleDiameter($Machine, [double] $Diameter) {
    if ($Machine.nozzle_diameter.Count -lt 2) { throw 'Machine template requires at least two toolheads' }
    $value = $Diameter.ToString('0.00', $Invariant)
    $Machine.nozzle_diameter[1] = $value
    foreach ($property in $Machine.PSObject.Properties) {
        if ($property.Name -notmatch '^toolhead_.*_line_width$') { continue }
        if ($null -ne $property.Value -and $property.Value.Count -ge 2) {
            $property.Value[1] = $value
        }
    }
}

$domains = [ordered]@{
    model = @('20mm_cube.obj','cube_with_hole.obj','overhang.obj','bridge.obj','multinozzle_feature_matrix.obj','small_nozzle_geometry_probe.stl')
    layer_height = @('0.12','0.20','0.28')
    wall_generator = @('classic','arachne')
    wall_loops = @('1','2','4','6')
    infill_pattern = @('rectilinear','grid','triangles','cubic','gyroid','concentric','adaptivecubic','lightning')
    infill_density = @('0%','10%','25%','50%','80%')
    infill_direction = @('0','30','45','90')
    nozzle2 = @(0.15,0.20,0.60,0.80)
    boolean = @($false,$true)
    detail_walls = @('0','1','3','6')
    overlap = @('0%','15%','40%','80%')
    support_type = @('normal(auto)','normal_cura(auto)','tree(auto)')
    support_angle = @('30','55','70','90')
    support_base_pattern = @('rectilinear','rectilinear-grid','honeycomb','lightning','hollow')
    interface_pattern = @('auto','rectilinear','concentric','grid','triangles')
    interface_layers = @('1','3','5')
    interface_spacing = @('0','0.2','0.5','1.0')
    sublayer_pattern = @('rectilinear','grid','triangles','concentric')
    sublayer_angle = @('0','30','60','120')
    tree_walls = @('0','1','3','10')
}

$random = [Random]::new($Seed)
$cases = [Collections.Generic.List[object]]::new()
for ($index = 0; $index -lt $CaseCount; ++$index) {
    $supportEnabled = [bool](Select-RandomValue $random $domains.boolean)
    $supportType = [string](Select-RandomValue $random $domains.support_type)
    $interfaceLayers = [int](Select-RandomValue $random $domains.interface_layers)
    $sublayerEnabled = $supportEnabled -and $interfaceLayers -gt 1 -and [bool](Select-RandomValue $random $domains.boolean)
    $smallNozzleEnabled = [bool](Select-RandomValue $random $domains.boolean)
    $override = if ($smallNozzleEnabled -and $random.Next(0,4) -eq 0) { @('1:5:1') } else { @() }
    $cases.Add([pscustomobject][ordered]@{
        id = ('cpu-{0:d4}' -f ($index + 1))
        model = [string](Select-RandomValue $random $domains.model)
        layer_height = [string](Select-RandomValue $random $domains.layer_height)
        wall_generator = [string](Select-RandomValue $random $domains.wall_generator)
        wall_loops = [string](Select-RandomValue $random $domains.wall_loops)
        sparse_infill_pattern = [string](Select-RandomValue $random $domains.infill_pattern)
        sparse_infill_density = [string](Select-RandomValue $random $domains.infill_density)
        infill_direction = [string](Select-RandomValue $random $domains.infill_direction)
        nozzle2 = [double](Select-RandomValue $random $domains.nozzle2)
        use_small_nozzle = $smallNozzleEnabled
        detail_walls = [string](Select-RandomValue $random $domains.detail_walls)
        interlocking = [bool](Select-RandomValue $random $domains.boolean)
        overlap = [string](Select-RandomValue $random $domains.overlap)
        override_regions = $override
        support_enabled = $supportEnabled
        support_type = $supportType
        support_angle = [string](Select-RandomValue $random $domains.support_angle)
        support_base_pattern = [string](Select-RandomValue $random $domains.support_base_pattern)
        interface_pattern = [string](Select-RandomValue $random $domains.interface_pattern)
        interface_layers = [string]$interfaceLayers
        interface_spacing = [string](Select-RandomValue $random $domains.interface_spacing)
        sublayer_enabled = $sublayerEnabled
        sublayer_start = '2'
        sublayer_end = if ($sublayerEnabled) { [string]$random.Next(2, $interfaceLayers + 3) } else { '2' }
        sublayer_pattern = [string](Select-RandomValue $random $domains.sublayer_pattern)
        sublayer_angle = [string](Select-RandomValue $random $domains.sublayer_angle)
        cura_raft = $supportEnabled -and $supportType -eq 'normal_cura(auto)' -and [bool](Select-RandomValue $random $domains.boolean)
        tree_walls = if ($supportEnabled -and $supportType -eq 'tree(auto)') { [string](Select-RandomValue $random $domains.tree_walls) } else { '0' }
    })
}

$planPath = Join-Path $runRoot 'case-plan.json'
[ordered]@{ schema=1; seed=$Seed; case_count=$CaseCount; domains=$domains; cases=$cases } |
    ConvertTo-Json -Depth 20 |
    Set-Content -LiteralPath $planPath -Encoding UTF8

$coverage = [Collections.Generic.List[object]]::new()
foreach ($property in @('model','layer_height','wall_generator','wall_loops','sparse_infill_pattern','sparse_infill_density','infill_direction','nozzle2','support_type','support_angle','support_base_pattern','interface_pattern','interface_layers','interface_spacing','sublayer_pattern','sublayer_angle','tree_walls')) {
    $values = @($cases | ForEach-Object { $_.$property } | Sort-Object -Unique)
    $coverage.Add([pscustomobject]@{ variable=$property; distinct=$values.Count; values=($values -join ',') })
}
$coverage | Export-Csv -LiteralPath (Join-Path $runRoot 'coverage.csv') -NoTypeInformation -Encoding UTF8

Write-Output "PLAN=$planPath"
Write-Output "CASES=$CaseCount SEED=$Seed"
if ($PlanOnly) { exit 0 }

$machineTemplate = Join-Path $RepoRoot 'sandboxes\multinozzle_test\auto_tool2_020_base1_machine.json'
$processTemplate = Join-Path $RepoRoot 'sandboxes\multinozzle_test\auto_tool2_020_base1_process.json'
$modelRoot = Join-Path $RepoRoot 'tests\data'
foreach ($required in @($SlicerPath,$machineTemplate,$processTemplate)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) { throw "Required file not found: $required" }
}
$filaments = @('Snapmaker PLA @U1','Snapmaker ABS @U1','Snapmaker PETG @U1','Snapmaker TPU @U1') |
    ForEach-Object { Find-FilamentProfile $_ }
$results = [Collections.Generic.List[object]]::new()
$originalDiagnosticsPath = [Environment]::GetEnvironmentVariable('MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE', 'Process')

foreach ($case in $cases) {
    $caseRoot = Join-Path $runRoot $case.id
    New-Item -ItemType Directory -Force -Path $caseRoot | Out-Null
    $machine = Get-Content -LiteralPath $machineTemplate -Raw | ConvertFrom-Json
    $process = Get-Content -LiteralPath $processTemplate -Raw | ConvertFrom-Json
    Set-NozzleDiameter $machine $case.nozzle2

    Set-JsonProperty $process 'layer_height' $case.layer_height
    Set-JsonProperty $process 'wall_generator' $case.wall_generator
    Set-JsonProperty $process 'wall_loops' $case.wall_loops
    Set-JsonProperty $process 'sparse_infill_pattern' $case.sparse_infill_pattern
    Set-JsonProperty $process 'sparse_infill_density' $case.sparse_infill_density
    Set-JsonProperty $process 'infill_direction' $case.infill_direction
    Set-JsonProperty $process 'use_smaller_nozzles_in_crisp_corners' $(if ($case.use_small_nozzle) { '1' } else { '0' })
    Set-JsonProperty $process 'crisp_corner_detail_toolhead' '2'
    Set-JsonProperty $process 'crisp_corner_small_nozzle_wall_count' $case.detail_walls
    Set-JsonProperty $process 'crisp_corner_interlace_small_nozzle_walls' $(if ($case.interlocking) { '1' } else { '0' })
    Set-JsonProperty $process 'crisp_corner_nozzle_wall_overlap' $case.overlap
    Set-JsonProperty $process 'crisp_corner_large_nozzle_override_regions' @($case.override_regions)
    Set-JsonProperty $process 'enable_support' $(if ($case.support_enabled) { '1' } else { '0' })
    Set-JsonProperty $process 'support_type' $case.support_type
    Set-JsonProperty $process 'support_threshold_angle' $case.support_angle
    Set-JsonProperty $process 'support_base_pattern' $case.support_base_pattern
    Set-JsonProperty $process 'support_interface_pattern' $case.interface_pattern
    Set-JsonProperty $process 'support_interface_top_layers' $case.interface_layers
    Set-JsonProperty $process 'support_interface_bottom_layers' '0'
    Set-JsonProperty $process 'support_interface_spacing' $case.interface_spacing
    Set-JsonProperty $process 'support_interface_sublayer_pattern' $(if ($case.sublayer_enabled) { '1' } else { '0' })
    Set-JsonProperty $process 'support_interface_sublayer_start_layer' $case.sublayer_start
    Set-JsonProperty $process 'support_interface_sublayer_end_layer' $case.sublayer_end
    Set-JsonProperty $process 'support_interface_sublayer_pattern_type' $case.sublayer_pattern
    Set-JsonProperty $process 'support_interface_sublayer_angle' $case.sublayer_angle
    Set-JsonProperty $process 'support_interface_sublayer_temperature' '0'
    Set-JsonProperty $process 'cura_solid_support_raft' $(if ($case.cura_raft) { '1' } else { '0' })
    Set-JsonProperty $process 'tree_support_wall_count' $case.tree_walls
    Set-JsonProperty $process 'single_nozzle_low_temperature_interface' '0'

    $machinePath = Join-Path $caseRoot 'machine.json'
    $processPath = Join-Path $caseRoot 'process.json'
    $machine | ConvertTo-Json -Depth 100 | Set-Content -LiteralPath $machinePath -Encoding UTF8
    $process | ConvertTo-Json -Depth 100 | Set-Content -LiteralPath $processPath -Encoding UTF8
    $modelPath = Join-Path $modelRoot $case.model
    if (-not (Test-Path -LiteralPath $modelPath -PathType Leaf)) { throw "Model not found: $modelPath" }

    $settings = [char]34 + "$machinePath;$processPath" + [char]34
    $loadedFilaments = [char]34 + ($filaments -join ';') + [char]34
    $arguments = @('--slice','0','--debug','1','--load-settings',$settings,'--load-filaments',$loadedFilaments,
                   '--outputdir',([char]34 + $caseRoot + [char]34),([char]34 + $modelPath + [char]34))
    $stdout = Join-Path $caseRoot 'cli.stdout.log'
    $stderr = Join-Path $caseRoot 'cli.stderr.log'
    if ($PerCaseVulkanDiagnostics) {
        $env:MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE = Join-Path $caseRoot 'vulkan-dispatch.csv'
    }
    $timer = [Diagnostics.Stopwatch]::StartNew()
    $handle = Start-Process -FilePath $SlicerPath -ArgumentList $arguments -NoNewWindow -PassThru `
        -RedirectStandardOutput $stdout -RedirectStandardError $stderr
    $timedOut = -not $handle.WaitForExit($SliceTimeoutSeconds * 1000)
    if ($timedOut) {
        & taskkill.exe /PID $handle.Id /T /F 2>$null | Out-Null
    }
    $timer.Stop()
    $gcode = Get-ChildItem -LiteralPath $caseRoot -File -Filter '*.gcode' | Select-Object -First 1
    $errors = [Collections.Generic.List[string]]::new()
    if ($timedOut) { $errors.Add("Timed out after $SliceTimeoutSeconds seconds") }
    if ($null -eq $gcode) { $errors.Add('G-code was not generated') }
    $analysis = if ($null -ne $gcode) { Analyze-Gcode $gcode.FullName } else { $null }
    if ($null -ne $analysis) {
        if ($analysis.motion_commands -eq 0 -or $analysis.extrusion_commands -eq 0) { $errors.Add('Printable motion is empty') }
        if ($analysis.non_finite -gt 0) { $errors.Add('G-code contains non-finite values') }
    }
    $results.Add([pscustomobject][ordered]@{
        id = $case.id
        passed = $errors.Count -eq 0
        seconds = [Math]::Round($timer.Elapsed.TotalSeconds, 3)
        errors = @($errors)
        settings_sha256 = (Get-FileHash -LiteralPath $processPath -Algorithm SHA256).Hash.ToLowerInvariant()
        canonical_sha256 = if ($analysis) { $analysis.canonical_sha256 } else { '' }
        motion_sha256 = if ($analysis) { $analysis.motion_sha256 } else { '' }
        bytes = if ($analysis) { $analysis.bytes } else { 0 }
        lines = if ($analysis) { $analysis.lines } else { 0 }
        motion_commands = if ($analysis) { $analysis.motion_commands } else { 0 }
        extrusion_commands = if ($analysis) { $analysis.extrusion_commands } else { 0 }
        tool_changes = if ($analysis) { $analysis.tool_changes } else { 0 }
    })
    if ($results.Count % 10 -eq 0 -or $errors.Count -gt 0) {
        $failedSoFar = @($results | Where-Object { -not $_.passed }).Count
        Write-Output "PROGRESS=$($results.Count)/$CaseCount FAILED=$failedSoFar LAST=$($case.id) SECONDS=$([Math]::Round($timer.Elapsed.TotalSeconds,2))"
    }
}

if ($PerCaseVulkanDiagnostics) {
    if ([string]::IsNullOrEmpty($originalDiagnosticsPath)) {
        Remove-Item Env:MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE -ErrorAction SilentlyContinue
    } else {
        $env:MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE = $originalDiagnosticsPath
    }
}

$resultPath = Join-Path $runRoot 'results.json'
$results | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $resultPath -Encoding UTF8
$results | Export-Csv -LiteralPath (Join-Path $runRoot 'summary.csv') -NoTypeInformation -Encoding UTF8
$failed = @($results | Where-Object { -not $_.passed })
$manifest = [ordered]@{
    schema = 1
    kind = 'magpie-vulkan-cpu-random-matrix'
    seed = $Seed
    case_count = $CaseCount
    git_head = (& git -C $RepoRoot rev-parse HEAD).Trim()
    slicer_sha256 = (Get-FileHash -LiteralPath $SlicerPath -Algorithm SHA256).Hash.ToLowerInvariant()
    plan = 'case-plan.json'
    results = 'results.json'
    passed = $CaseCount - $failed.Count
    failed = $failed.Count
}
$manifest | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $runRoot 'baseline-manifest.json') -Encoding UTF8
Write-Output "RUN_ROOT=$runRoot"
Write-Output "RESULTS=$resultPath"
Write-Output "PASSED=$($manifest.passed) FAILED=$($manifest.failed)"
if ($failed.Count -gt 0) { exit 1 }
