param(
    [string] $SpatialRoot = "",
    [int] $SliceTimeoutSeconds = 300
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($SpatialRoot)) {
    $SpatialRoot = (Get-Content -LiteralPath (Join-Path $RepoRoot 'build\verification\cura-spatial-filter-current.txt') -Raw).Trim()
}

$CurrentRoot = Join-Path $SpatialRoot 'current-11-suite'
$GeometryRoot = Join-Path $CurrentRoot 'geometry'
$RaftRoot = Join-Path $CurrentRoot 'solid-raft'
$MatrixRoot = Join-Path $SpatialRoot 'boundary-matrix'
$Executable = (Resolve-Path (Join-Path $RepoRoot 'build-vulkan\src\Release\magpie-slicer.exe')).Path
$Reference = (Resolve-Path (Join-Path $RepoRoot 'build\verification\cura-support-runtime-20260806-162220\optimized-1')).Path
$ExpectedDllHash = 'D13D2A8242BD69FF9E612358A32F7C7F6F450BCCDE8F5FDBF122AFC543F90592'
New-Item -ItemType Directory -Force $CurrentRoot | Out-Null

function Normalize-Line([string] $Line) {
    if ($Line -match '^; generated by OrcaSlicer .* on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$') {
        return '; generated by OrcaSlicer <normalized>'
    }
    return $Line -replace '(; (?:stop )?printing object .* id:)\d+( copy \d+)', '$1<ID>$2'
}

function Get-CanonicalHash([string] $Path) {
    $Temporary = [IO.Path]::GetTempFileName()
    try {
        $Writer = [IO.StreamWriter]::new($Temporary, $false, [Text.UTF8Encoding]::new($false))
        try {
            foreach ($Line in [IO.File]::ReadLines($Path)) {
                $Writer.WriteLine((Normalize-Line $Line))
            }
        } finally {
            $Writer.Dispose()
        }
        return (Get-FileHash -LiteralPath $Temporary -Algorithm SHA256).Hash
    } finally {
        Remove-Item -LiteralPath $Temporary -Force -ErrorAction SilentlyContinue
    }
}

function Get-HashMultiset([string[]] $Files) {
    $Map = @{}
    foreach ($File in $Files) {
        $Hash = Get-CanonicalHash $File
        if (-not $Map.ContainsKey($Hash)) { $Map[$Hash] = 0 }
        ++$Map[$Hash]
    }
    return $Map
}

if (Get-Process -Name 'magpie-slicer' -ErrorAction SilentlyContinue) {
    throw 'magpie-slicer is already running before regression stage'
}

Write-Output '[1/4] Generate Cura geometry suite'
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'verify_cura_support_geometry.ps1') `
    -SlicerPath $Executable -OutputRoot $GeometryRoot -SliceTimeoutSeconds $SliceTimeoutSeconds
if ($LASTEXITCODE -ne 0) { throw "Geometry suite failed: $LASTEXITCODE" }

Write-Output '[2/4] Generate Cura solid-raft suite'
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'verify_cura_solid_support_raft.ps1') `
    -Executable $Executable -OutputRoot $RaftRoot
if ($LASTEXITCODE -ne 0) { throw "Solid raft suite failed: $LASTEXITCODE" }

Write-Output '[3/4] Canonical 11-file comparison'
$CurrentFiles = @(Get-ChildItem -LiteralPath $CurrentRoot -Recurse -File -Filter '*.gcode' | Select-Object -ExpandProperty FullName)
$ReferenceFiles = @(Get-ChildItem -LiteralPath $Reference -Recurse -File -Filter '*.gcode' | Select-Object -ExpandProperty FullName)
Write-Output "CURRENT_FILES=$($CurrentFiles.Count) REFERENCE_FILES=$($ReferenceFiles.Count)"
if ($CurrentFiles.Count -ne 11 -or $ReferenceFiles.Count -ne 11) {
    throw 'Expected exactly 11 current and 11 reference G-code files'
}
foreach ($File in $CurrentFiles) {
    $Invalid = Select-String -LiteralPath $File -Pattern '(?i)(^|[^A-Za-z])(nan|[-+]?inf(?:inity)?)([^A-Za-z]|$)' -AllMatches
    if ($Invalid) { throw "Invalid numeric token in $File" }
}

$Expected = Get-HashMultiset $ReferenceFiles
$Actual = Get-HashMultiset $CurrentFiles
if ($Expected.Count -ne $Actual.Count) { throw 'Canonical hash-set cardinality mismatch' }
foreach ($Key in $Expected.Keys) {
    if (-not $Actual.ContainsKey($Key) -or $Expected[$Key] -ne $Actual[$Key]) {
        throw "Canonical G-code mismatch: $Key"
    }
}
Write-Output 'PASS CURRENT_11_EQUALS_PREVIOUS_11'

Write-Output '[4/4] Boundary matrix baseline/current comparison'
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'verify_cura_support_optimization_matrix.ps1') `
    -OutputRoot $MatrixRoot -SliceTimeoutSeconds $SliceTimeoutSeconds
if ($LASTEXITCODE -ne 0) { throw "Boundary matrix failed: $LASTEXITCODE" }

$ActiveHash = (Get-FileHash (Join-Path $RepoRoot 'build-vulkan\src\Release\MagpieSlicer.dll') -Algorithm SHA256).Hash
Write-Output "ACTIVE_DLL_HASH=$ActiveHash"
if ($ActiveHash -ne $ExpectedDllHash) { throw 'Active DLL was not restored after matrix' }
if (Get-Process -Name 'magpie-slicer' -ErrorAction SilentlyContinue) {
    throw 'Residual magpie-slicer process after regression stage'
}
Write-Output 'REGRESSION_STAGE=PASS'
