param(
    [string] $RuntimeRoot = "",
    [string] $Executable = "build-vulkan/src/Release/magpie-slicer.exe",
    [int] $SliceTimeoutSeconds = 300
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($RuntimeRoot)) {
    $RuntimeRoot = Get-ChildItem (Join-Path $RepoRoot 'build/verification') -Directory |
        Where-Object { $_.Name -like 'cura-support-runtime-*' } |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1 -ExpandProperty FullName
}
if (-not [IO.Path]::IsPathRooted($Executable))
    { $Executable = Join-Path $RepoRoot $Executable }

$Executable = (Resolve-Path $Executable).Path
$RuntimeRoot = (Resolve-Path $RuntimeRoot).Path
$ReleaseRoot = Split-Path $Executable
$Machine = (Resolve-Path (Join-Path $RepoRoot 'build/verification/cura-bunny-support-top/20260723-173708/machine.json')).Path
$ProcessConfig = (Resolve-Path (Join-Path $RepoRoot 'build/verification/support-performance-20260806-141527/cura/process.json')).Path
$Model = (Resolve-Path (Join-Path $RepoRoot 'resources/handy_models/Stanford_Bunny.drc')).Path
$HistoricalGcode = (Resolve-Path (Join-Path $RepoRoot 'build/verification/support-performance-20260806-141527/cura/plate_1.gcode')).Path

function Normalize-Line([string] $Line) {
    if ($Line -match '^; generated by OrcaSlicer .* on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$') {
        return '; generated by OrcaSlicer <normalized>'
    }
    return $Line -replace '(; (?:stop )?printing object .* id:)\d+( copy \d+)', '$1<ID>$2'
}

function Get-CanonicalHash([string] $Path) {
    $Temporary = [IO.Path]::GetTempFileName()
    try {
        $Writer = New-Object IO.StreamWriter($Temporary, $false, (New-Object Text.UTF8Encoding($false)))
        try {
            foreach ($Line in [IO.File]::ReadLines($Path)) {
                $Writer.WriteLine((Normalize-Line $Line))
            }
        } finally {
            $Writer.Dispose()
        }
        return (Get-FileHash -LiteralPath $Temporary -Algorithm SHA256).Hash
    } finally {
        Remove-Item -LiteralPath $Temporary -Force -ErrorAction SilentlyContinue
    }
}

function Get-LogicalKey([string] $Base, [string] $Path) {
    $Key = $Path.Substring($Base.Length).TrimStart('\', '/')
    $Key = $Key -replace '(^|[\\/])\d{8}-\d{6}([\\/])', '$1'
    return ($Key -replace '\\', '/').ToLowerInvariant()
}

function Get-GcodeMap([string] $Directory) {
    $Base = (Resolve-Path $Directory).Path
    $Map = @{}
    foreach ($File in Get-ChildItem $Base -Recurse -Filter '*.gcode' -File) {
        $Key = Get-LogicalKey $Base $File.FullName
        if ($Map.ContainsKey($Key)) { throw "Duplicate logical G-code key: $Key" }
        $Map[$Key] = Get-CanonicalHash $File.FullName
    }
    return $Map
}

function Assert-MapsEqual([hashtable] $Expected, [hashtable] $Actual, [string] $Label) {
    if ($Expected.Count -ne $Actual.Count) { throw "$Label file count mismatch" }
    foreach ($Key in $Expected.Keys) {
        if (-not $Actual.ContainsKey($Key) -or $Expected[$Key] -ne $Actual[$Key]) {
            throw "$Label machine-content mismatch: $Key"
        }
    }
    Write-Output "PASS $Label files=$($Expected.Count)"
}

function Wait-Slice([Diagnostics.Process] $Process, [string] $GcodePath, [int] $TimeoutSeconds) {
    $Deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    $LastLength = -1L
    $StableSamples = 0
    while ([DateTime]::UtcNow -lt $Deadline) {
        if (Test-Path $GcodePath) {
            $Length = (Get-Item $GcodePath).Length
            if ($Length -gt 0 -and $Length -eq $LastLength) {
                ++$StableSamples
            } else {
                $StableSamples = 0
                $LastLength = $Length
            }
            if ($StableSamples -ge 3 -and (Get-Content $GcodePath -Tail 12) -match 'CONFIG_BLOCK_END') {
                if (-not $Process.HasExited -and -not $Process.WaitForExit(5000)) {
                    Stop-Process -Id $Process.Id -Force
                }
                return Get-Item $GcodePath
            }
        }
        $Process.Refresh()
        if ($Process.HasExited -and -not (Test-Path $GcodePath)) {
            throw "Slice process exited without G-code: PID $($Process.Id)"
        }
        if ([DateTime]::UtcNow -ge $Deadline) {
            Stop-Process -Id $Process.Id -Force
            throw "Slice timeout: PID $($Process.Id)"
        }
        Start-Sleep -Milliseconds 500
    }
    throw "G-code did not complete: $GcodePath"
}

$BaselineMap = Get-GcodeMap (Join-Path $RuntimeRoot 'baseline-1')
$OptimizedMap = Get-GcodeMap (Join-Path $RuntimeRoot 'optimized-1')
Assert-MapsEqual $BaselineMap $OptimizedMap 'baseline-vs-optimized'
for ($Repeat = 2; $Repeat -le 4; ++$Repeat) {
    Assert-MapsEqual $OptimizedMap (Get-GcodeMap (Join-Path $RuntimeRoot "optimized-$Repeat")) "optimized-repeat-1-vs-$Repeat"
}

$Times = @()
$Files = @()
$PerformanceRoot = Join-Path $RuntimeRoot ("bunny-performance-" + (Get-Date -Format 'yyyyMMdd-HHmmss'))
for ($Run = 1; $Run -le 3; ++$Run) {
    $Output = Join-Path $PerformanceRoot "run-$Run"
    New-Item -ItemType Directory -Path $Output -Force | Out-Null
    $GcodePath = Join-Path $Output 'plate_1.gcode'
    $Arguments = @('--slice', '0', '--debug', '1', '--load-settings', $Machine, '--load-settings', $ProcessConfig, '--outputdir', $Output, $Model)
    $Watch = [Diagnostics.Stopwatch]::StartNew()
    $Process = Start-Process -FilePath $Executable -ArgumentList $Arguments -WorkingDirectory $ReleaseRoot `
        -RedirectStandardOutput (Join-Path $Output 'stdout.log') `
        -RedirectStandardError (Join-Path $Output 'stderr.log') -PassThru
    $Gcode = Wait-Slice $Process $GcodePath $SliceTimeoutSeconds
    $Watch.Stop()

    $NonFinite = Select-String -Path $Gcode.FullName -Pattern '(?i)(?:^|[^a-z])(nan|inf)(?:[^a-z]|$)' -List
    if ($null -ne $NonFinite) { throw "Non-finite G-code at line $($NonFinite.LineNumber)" }
    $Times += $Watch.Elapsed.TotalSeconds
    $Files += $Gcode.FullName
    Write-Output ("BUNNY run={0} seconds={1:N3} bytes={2}" -f $Run, $Watch.Elapsed.TotalSeconds, $Gcode.Length)
}

$Hashes = @($Files | ForEach-Object { Get-CanonicalHash $_ })
if (@($Hashes | Select-Object -Unique).Count -ne 1) { throw 'Bunny repeated outputs differ' }
if ((Get-CanonicalHash $HistoricalGcode) -ne $Hashes[0]) { throw 'Historical and optimized Bunny outputs differ' }

$SortedTimes = @($Times | Sort-Object)
$Median = $SortedTimes[1]
$HistoricalSeconds = 10.615
$Summary = [pscustomobject]@{
    SuiteFiles = $BaselineMap.Count
    SuiteRuns = 5
    BunnyRuns = 3
    BunnyTimesSeconds = $Times
    BunnyMedianSeconds = $Median
    HistoricalSeconds = $HistoricalSeconds
    DeltaRatio = ($Median / $HistoricalSeconds) - 1
    CanonicalHash = $Hashes[0]
    ActiveDllHash = (Get-FileHash (Join-Path $ReleaseRoot 'MagpieSlicer.dll') -Algorithm SHA256).Hash
}
$SummaryPath = Join-Path $RuntimeRoot 'summary.json'
$Summary | ConvertTo-Json -Depth 4 | Set-Content $SummaryPath -Encoding utf8
Write-Output ("PASS Bunny deterministic and baseline-identical; median={0:N3}s, historical={1:N3}s, delta={2:P1}" -f $Median, $HistoricalSeconds, $Summary.DeltaRatio)
Write-Output "SUMMARY=$SummaryPath"
