param(
    [string] $OutputRoot = "",
    [int] $SliceTimeoutSeconds = 180
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    $OutputRoot = Join-Path $RepoRoot ("build/verification/cura-support-boundary-matrix-" + (Get-Date -Format 'yyyyMMdd-HHmmss'))
}
New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null

$ReleaseRoot = (Resolve-Path (Join-Path $RepoRoot 'build-vulkan/src/Release')).Path
$Executable = Join-Path $ReleaseRoot 'magpie-slicer.exe'
$LiveDll = Join-Path $ReleaseRoot 'MagpieSlicer.dll'
$OptimizedDll = Join-Path $OutputRoot 'MagpieSlicer.optimized.dll'
Copy-Item $LiveDll $OptimizedDll
$BaselineRoot = Get-ChildItem (Join-Path $RepoRoot 'build/verification') -Directory |
    Where-Object { $_.Name -like 'cura-optimization-*' -and (Test-Path (Join-Path $_.FullName 'baseline/MagpieSlicer.dll')) } |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
if ($null -eq $BaselineRoot) { throw 'Preserved baseline DLL not found' }
$BaselineDll = Join-Path $BaselineRoot.FullName 'baseline/MagpieSlicer.dll'

$BaseCase = Join-Path $RepoRoot 'build/verification/support-post-lowtemp-fix-20260728-213109/20260728-213110/cura_90_triangles'
$BaseMachine = Join-Path $BaseCase 'machine.json'
$BaseProcess = Join-Path $BaseCase 'process.json'
$Model = Join-Path $RepoRoot 'tests/data/overhang.obj'

$Cases = @(
    @{ Name='auto_angle_1'; Values=@{ support_type='normal_cura(auto)'; support_threshold_angle='1' } },
    @{ Name='auto_angle_90'; Values=@{ support_type='normal_cura(auto)'; support_threshold_angle='90' } },
    @{ Name='auto_xy_gap_0'; Values=@{ support_type='normal_cura(auto)'; support_object_xy_distance='0' } },
    @{ Name='auto_xy_gap_2'; Values=@{ support_type='normal_cura(auto)'; support_object_xy_distance='2' } },
    @{ Name='auto_expansion_neg1'; Values=@{ support_type='normal_cura(auto)'; support_expansion='-1' } },
    @{ Name='auto_expansion_5'; Values=@{ support_type='normal_cura(auto)'; support_expansion='5' } },
    @{ Name='auto_buildplate_only'; Values=@{ support_type='normal_cura(auto)'; support_on_build_plate_only='1' } },
    @{ Name='auto_no_interface'; Values=@{ support_type='normal_cura(auto)'; support_interface_top_layers='0'; support_interface_bottom_layers='0' } },
    @{ Name='auto_top_bottom_interface'; Values=@{ support_type='normal_cura(auto)'; support_interface_top_layers='5'; support_interface_bottom_layers='3' } },
    @{ Name='manual_empty_channel'; Values=@{ support_type='normal_cura(manual)'; support_interface_top_layers='0'; support_interface_bottom_layers='0' }; ExpectSupport=$false }
)

function Set-JsonProperty($Object, [string] $Name, $Value) {
    $Object | Add-Member -MemberType NoteProperty -Name $Name -Value $Value -Force
}

function Wait-GCode([Diagnostics.Process] $Process, [string] $Path, [int] $TimeoutSeconds) {
    $Deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    $LastLength = -1L
    $Stable = 0
    while ([DateTime]::UtcNow -lt $Deadline) {
        if (Test-Path $Path) {
            $Length = (Get-Item $Path).Length
            if ($Length -gt 0 -and $Length -eq $LastLength) { ++$Stable } else { $Stable = 0; $LastLength = $Length }
            if ($Stable -ge 3 -and (Get-Content $Path -Tail 12) -match 'CONFIG_BLOCK_END') {
                if (-not $Process.HasExited -and -not $Process.WaitForExit(5000)) { Stop-Process -Id $Process.Id -Force }
                return
            }
        }
        $Process.Refresh()
        if ($Process.HasExited -and -not (Test-Path $Path)) { throw "Process exited without G-code: $Path" }
        Start-Sleep -Milliseconds 500
    }
    if (-not $Process.HasExited) { Stop-Process -Id $Process.Id -Force }
    throw "G-code timeout: $Path"
}

function Normalize-Line([string] $Line) {
    if ($Line -match '^; generated by OrcaSlicer .* on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$') { return '; generated by OrcaSlicer <normalized>' }
    return $Line -replace '(; (?:stop )?printing object .* id:)\d+( copy \d+)', '$1<ID>$2'
}

function Get-CanonicalHash([string] $Path) {
    $Temporary = [IO.Path]::GetTempFileName()
    try {
        $Writer = New-Object IO.StreamWriter($Temporary, $false, (New-Object Text.UTF8Encoding($false)))
        try { foreach ($Line in [IO.File]::ReadLines($Path)) { $Writer.WriteLine((Normalize-Line $Line)) } }
        finally { $Writer.Dispose() }
        return (Get-FileHash $Temporary -Algorithm SHA256).Hash
    } finally { Remove-Item $Temporary -Force -ErrorAction SilentlyContinue }
}

function Invoke-Matrix([string] $Dll, [string] $Label) {
    Copy-Item $Dll $LiveDll -Force
    $Results = @()
    foreach ($Case in $Cases) {
        $CaseRoot = Join-Path $OutputRoot (Join-Path $Label $Case.Name)
        New-Item -ItemType Directory -Path $CaseRoot -Force | Out-Null
        $MachinePath = Join-Path $CaseRoot 'machine.json'
        $ProcessPath = Join-Path $CaseRoot 'process.json'
        $GcodePath = Join-Path $CaseRoot 'plate_1.gcode'
        Copy-Item $BaseMachine $MachinePath
        $ProcessConfig = Get-Content $BaseProcess -Raw | ConvertFrom-Json
        foreach ($Entry in $Case.Values.GetEnumerator()) { Set-JsonProperty $ProcessConfig $Entry.Key $Entry.Value }
        $ProcessConfig | ConvertTo-Json -Depth 100 | Set-Content $ProcessPath -Encoding utf8
        $Arguments = @('--slice', '0', '--debug', '1', '--load-settings', $MachinePath, '--load-settings', $ProcessPath, '--outputdir', $CaseRoot, $Model)
        $Handle = Start-Process -FilePath $Executable -ArgumentList $Arguments -WorkingDirectory $ReleaseRoot `
            -RedirectStandardOutput (Join-Path $CaseRoot 'stdout.log') -RedirectStandardError (Join-Path $CaseRoot 'stderr.log') -PassThru
        Wait-GCode $Handle $GcodePath $SliceTimeoutSeconds
        $NonFinite = Select-String $GcodePath -Pattern '(?i)(?:^|[^a-z])(nan|inf)(?:[^a-z]|$)' -List
        if ($null -ne $NonFinite) { throw "$Label/$($Case.Name) contains non-finite G-code" }
        $SupportMarkers = @(Select-String $GcodePath -Pattern '^;TYPE:Support(?: interface)?$').Count
        $ExpectSupport = if ($Case.ContainsKey('ExpectSupport')) { $Case.ExpectSupport } else { $true }
        if ($ExpectSupport -and $SupportMarkers -eq 0) { throw "$Label/$($Case.Name) generated no support" }
        if (-not $ExpectSupport -and $SupportMarkers -ne 0) { throw "$Label/$($Case.Name) unexpectedly generated support" }
        $Results += [pscustomobject]@{ Name=$Case.Name; Hash=(Get-CanonicalHash $GcodePath); Bytes=(Get-Item $GcodePath).Length; SupportMarkers=$SupportMarkers }
        Write-Output "PASS $Label/$($Case.Name) bytes=$((Get-Item $GcodePath).Length) support_markers=$SupportMarkers"
    }
    return $Results
}

try {
    $Baseline = Invoke-Matrix $BaselineDll 'baseline'
    $Optimized = Invoke-Matrix $OptimizedDll 'optimized'
    foreach ($Expected in $Baseline) {
        $Actual = $Optimized | Where-Object { $_.Name -eq $Expected.Name }
        if ($null -eq $Actual -or $Actual.Hash -ne $Expected.Hash) { throw "Matrix old/new mismatch: $($Expected.Name)" }
    }
    [pscustomobject]@{ Cases=$Cases.Count; BaselineDll=(Get-FileHash $BaselineDll -Algorithm SHA256).Hash; OptimizedDll=(Get-FileHash $OptimizedDll -Algorithm SHA256).Hash; Passed=$true } |
        ConvertTo-Json | Set-Content (Join-Path $OutputRoot 'summary.json') -Encoding utf8
    Write-Output "PASS boundary matrix old/new identical cases=$($Cases.Count)"
} finally {
    Copy-Item $OptimizedDll $LiveDll -Force
}
Write-Output "RESULT_ROOT=$OutputRoot"
