param(
    [string] $RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [Parameter(Mandatory = $true)]
    [string] $SourceCase,
    [Parameter(Mandatory = $true)]
    [string] $ModelPath,
    [string] $SlicerPath = "",
    [string] $OutputRoot = "",
    [ValidateRange(2, 10)]
    [int] $Repeats = 3,
    [ValidateRange(10, 600)]
    [int] $SliceTimeoutSeconds = 180
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$RepoRoot = [IO.Path]::GetFullPath($RepoRoot)
$SourceCase = [IO.Path]::GetFullPath($SourceCase)
$ModelPath = [IO.Path]::GetFullPath($ModelPath)
if ([string]::IsNullOrWhiteSpace($SlicerPath)) {
    $SlicerPath = Join-Path $RepoRoot 'build-vulkan\src\Release\magpie-slicer-vulkan-test.exe'
}
if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    $OutputRoot = Join-Path $RepoRoot 'build-vulkan\verification\vulkan-targeted-case'
}
$SlicerPath = [IO.Path]::GetFullPath($SlicerPath)
$OutputRoot = [IO.Path]::GetFullPath($OutputRoot)
$runRoot = Join-Path $OutputRoot (Get-Date -Format 'yyyyMMdd-HHmmss')
New-Item -ItemType Directory -Force -Path $runRoot | Out-Null

foreach ($required in @(
    $SlicerPath,
    $ModelPath,
    (Join-Path $SourceCase 'machine.json'),
    (Join-Path $SourceCase 'process.json'),
    (Join-Path $PSScriptRoot 'lib\GcodeGeometryAnalyzer.cs')
)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "Required file not found: $required"
    }
}
Add-Type -Path (Join-Path $PSScriptRoot 'lib\GcodeGeometryAnalyzer.cs')

function Find-FilamentProfile([string] $Name) {
    foreach ($root in @(
        (Join-Path $RepoRoot 'resources\profiles'),
        (Join-Path $RepoRoot 'build-vulkan\src\Release\resources\profiles')
    )) {
        if (-not (Test-Path -LiteralPath $root -PathType Container)) { continue }
        $match = Get-ChildItem -LiteralPath $root -Recurse -File -Filter ($Name + '.json') | Select-Object -First 1
        if ($null -ne $match) { return $match.FullName }
    }
    throw "Filament profile not found: $Name"
}

function Get-TextSha256([string] $Text) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try {
        return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-', '').ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

function Get-MotionSha256([string] $Path) {
    $motion = [Text.StringBuilder]::new()
    foreach ($raw in [IO.File]::ReadLines($Path)) {
        $line = $raw.TrimEnd()
        if ($line -match '(?i)(^; generated by .+ on \d{4}-\d{2}-\d{2}|generated at|generation time|timestamp|creation date|slicing time|processing time)') {
            continue
        }
        $command = ($line -split ';', 2)[0].Trim()
        if ($command -match '^(?:G0|G1|G2|G3|G5|T\d+|M10[4679]|M106|M107)(?:\s|$)') {
            [void] $motion.Append($command).Append([char] 10)
        }
    }
    return Get-TextSha256 $motion.ToString()
}

$filaments = @('Snapmaker PLA @U1', 'Snapmaker ABS @U1', 'Snapmaker PETG @U1', 'Snapmaker TPU @U1') |
    ForEach-Object { Find-FilamentProfile $_ }
$settings = [char] 34 + ((Join-Path $SourceCase 'machine.json') + ';' + (Join-Path $SourceCase 'process.json')) + [char] 34
$loadedFilaments = [char] 34 + ($filaments -join ';') + [char] 34
$savedEnvironment = @{}
foreach ($name in @(
    'MAGPIE_VULKAN_SLICER_ENABLE',
    'MAGPIE_VULKAN_SLICER_GPU_PRIORITY',
    'MAGPIE_VULKAN_SLICER_FORCE_DISPATCH',
    'MAGPIE_VULKAN_SLICER_VALIDATION',
    'MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE'
)) {
    $savedEnvironment[$name] = [Environment]::GetEnvironmentVariable($name, 'Process')
}

$results = [Collections.Generic.List[object]]::new()
try {
    foreach ($mode in @('cpu', 'gpu')) {
        for ($repeat = 1; $repeat -le $Repeats; ++$repeat) {
            $id = '{0}-{1}' -f $mode, $repeat
            $caseRoot = Join-Path $runRoot $id
            New-Item -ItemType Directory -Force -Path $caseRoot | Out-Null

            if ($mode -eq 'gpu') {
                $env:MAGPIE_VULKAN_SLICER_ENABLE = '1'
                $env:MAGPIE_VULKAN_SLICER_GPU_PRIORITY = '1'
                $env:MAGPIE_VULKAN_SLICER_FORCE_DISPATCH = '1'
                $env:MAGPIE_VULKAN_SLICER_VALIDATION = 'strict'
                $env:MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE = Join-Path $caseRoot 'vulkan-dispatch.csv'
            } else {
                Remove-Item Env:MAGPIE_VULKAN_SLICER_ENABLE -ErrorAction SilentlyContinue
                Remove-Item Env:MAGPIE_VULKAN_SLICER_GPU_PRIORITY -ErrorAction SilentlyContinue
                Remove-Item Env:MAGPIE_VULKAN_SLICER_FORCE_DISPATCH -ErrorAction SilentlyContinue
                Remove-Item Env:MAGPIE_VULKAN_SLICER_DIAGNOSTICS_FILE -ErrorAction SilentlyContinue
            }

            $arguments = @(
                '--slice', '0', '--debug', '1',
                '--load-settings', $settings,
                '--load-filaments', $loadedFilaments,
                '--outputdir', ([char] 34 + $caseRoot + [char] 34),
                ([char] 34 + $ModelPath + [char] 34)
            )
            $stdout = Join-Path $caseRoot 'cli.stdout.log'
            $stderr = Join-Path $caseRoot 'cli.stderr.log'
            $timer = [Diagnostics.Stopwatch]::StartNew()
            $handle = Start-Process -FilePath $SlicerPath -ArgumentList $arguments -WindowStyle Hidden -PassThru `
                -RedirectStandardOutput $stdout -RedirectStandardError $stderr
            $timedOut = -not $handle.WaitForExit($SliceTimeoutSeconds * 1000)
            if ($timedOut) {
                & taskkill.exe /PID $handle.Id /T /F 2>$null | Out-Null
                throw "$id timed out after $SliceTimeoutSeconds seconds"
            }
            $timer.Stop()

            $gcode = Get-ChildItem -LiteralPath $caseRoot -File -Filter '*.gcode' | Select-Object -First 1
            if ($null -eq $gcode) {
                throw "$id did not generate G-code: $(Get-Content -LiteralPath $stderr -Raw)"
            }
            $geometry = [Magpie.Verification.GcodeGeometryAnalyzer]::Analyze($gcode.FullName, 0.05, $true)
            $diagnostics = Join-Path $caseRoot 'vulkan-dispatch.csv'
            $dispatches = if (Test-Path -LiteralPath $diagnostics) {
                @(Get-Content -LiteralPath $diagnostics | Where-Object { $_.Trim() }).Count
            } else { 0 }

            $results.Add([pscustomobject][ordered]@{
                id = $id
                mode = $mode
                repeat = $repeat
                seconds = [Math]::Round($timer.Elapsed.TotalSeconds, 3)
                gcode = $gcode.FullName
                motion_sha256 = Get-MotionSha256 $gcode.FullName
                segment_sha256 = $geometry.SegmentSha256
                coverage_sha256 = $geometry.CoverageSha256
                metrics_sha256 = $geometry.MetricsSha256
                positive_segments = $geometry.PositiveSegments
                coverage_cells = $geometry.CoverageCells
                total_length = $geometry.TotalLength
                total_extrusion = $geometry.TotalExtrusion
                vulkan_dispatches = $dispatches
            })
            Write-Output "COMPLETED=$id DISPATCHES=$dispatches"
        }
    }
} finally {
    foreach ($name in $savedEnvironment.Keys) {
        $value = $savedEnvironment[$name]
        if ($null -eq $value) {
            [Environment]::SetEnvironmentVariable($name, $null, 'Process')
        } else {
            [Environment]::SetEnvironmentVariable($name, $value, 'Process')
        }
    }
}

$cpu = @($results | Where-Object mode -eq 'cpu')
$gpu = @($results | Where-Object mode -eq 'gpu')
$cpuSignatures = @($cpu | ForEach-Object { $_.segment_sha256 + ':' + $_.coverage_sha256 + ':' + $_.metrics_sha256 } | Sort-Object -Unique)
$gpuSignatures = @($gpu | ForEach-Object { $_.segment_sha256 + ':' + $_.coverage_sha256 + ':' + $_.metrics_sha256 } | Sort-Object -Unique)
$crossMatches = 0
foreach ($left in $cpu) {
    foreach ($right in $gpu) {
        if ($left.segment_sha256 -eq $right.segment_sha256 -and
            $left.coverage_sha256 -eq $right.coverage_sha256 -and
            $left.metrics_sha256 -eq $right.metrics_sha256) {
            ++$crossMatches
        }
    }
}
$summary = [pscustomobject][ordered]@{
    schema = 1
    run_root = $runRoot
    repeats = $Repeats
    cpu_unique_geometry = $cpuSignatures.Count
    gpu_unique_geometry = $gpuSignatures.Count
    cross_geometry_matches = $crossMatches
    expected_cross_pairs = $Repeats * $Repeats
    results = @($results)
}
$summaryPath = Join-Path $runRoot 'targeted-summary.json'
$summary | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $summaryPath -Encoding UTF8
Write-Output "RESULT=$summaryPath"
Write-Output "CPU_UNIQUE=$($summary.cpu_unique_geometry) GPU_UNIQUE=$($summary.gpu_unique_geometry) CROSS_MATCHES=$crossMatches/$($summary.expected_cross_pairs)"
